"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""


def even_fib_sum():
	fib = [1,2]
	new_fib = fib[-1]+fib[-2]
	while new_fib <= 4000000:
		fib.append(new_fib)
		new_fib = fib[-1]+fib[-2]
	answer = sum(i for i in fib if i % 2==0)
	return answer

if __name__=="__main__":
	print(even_fib_sum())
